version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ylabonte"
    groups:
      dev-dependencies:
        dependency-type: "development"
      production:
        dependency-type: "production"
    versioning-strategy: "increase"
