name: "Auto-Merge Dependabot PRs"

on: [ pull_request ]

permissions:
  actions: read
  security-events: write
  contents: write
  pull-requests: write

jobs:
  ci:
    name: "Run CI Workflow"
    uses: ./.github/workflows/ci.yml
  automerge:
    name: "Auto-merge PR (Dependabot only!)"
    needs:
      - ci
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: "Auto-merge the PRs"
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
