name: "Auto-Merge Dependabot PRs"

on:
  pull_request:
    branches:
      - "master"

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    name: "Auto-approve PR"
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'ylabonte'
    steps:
      - name: "Approve PR to enable auto-merge"
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: "Auto-merge PR"
        run: gh pr merge --merge --auto "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
