name: "CI Workflow"

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - "master"
      - "develop"
      - "feature/*"
  workflow_call:

jobs:
  build:
    name: "Build and lint"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18
          - 20

    steps:
      - name: "Ensure line endings"
        run: git config --global core.autocrlf false
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Set up Node.js v${{ matrix.node-version }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: "Install dependencies"
        run: yarn
      - name: "Build"
        run: yarn run build
      - name: "Run linter"
        run: yarn run lint
