name: "Github Package Release"

on:
  workflow_run:
      workflows:
        - "NPM Package Release"
      types:
        - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup node environment"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
      - name: "Rewrite package.json for github publishing"
        run: |
          sed -i.orig "s/\(\"name\": \"\)\(procon-ip\"\)/\1@ylabonte\/\2/" package.json
      - name: "Setup dependencies"
        run: yarn
      - name: "Publish project on github.com"
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
