name: "NPM Package Release"

on:
  release:
    types: [ "created" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
    - uses: actions/checkout@v3

    - name: "Setup node environment"
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'

    - name: "Setup dependencies"
      run: npm ci

    - name: "Build and publish project on npmjs.com"
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
