name: Github Package Release
on:
  workflow_run:
      workflows: ["NPM Package Release"]
      types:
          - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 'latest'
        registry-url: 'https://npm.pkg.github.com'
    # Rewrite package.json to have the package name scoped for publishing to the github repo.
    - run: |
        sed -i.orig "s/\(\"name\": \"\)\(procon-ip\"\)/\1@ylabonte\/\2/" package.json
    - run: npm ci
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
